#!/usr/bin/env bash
# TitanBot Cloud Agent — durable setup (baked into the environment snapshot).
# Idempotent: safe to run repeatedly and against a partially prepared VM.
set -euo pipefail

echo "==> [install] Ensuring PostgreSQL is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib
fi

# Resolve the installed PostgreSQL major version (e.g. 16).
PGVER="$(ls /etc/postgresql 2>/dev/null | sort -n | tail -1)"
if [ -z "${PGVER:-}" ]; then
  echo "!! Could not determine PostgreSQL version under /etc/postgresql" >&2
  exit 1
fi

echo "==> [install] Starting PostgreSQL ${PGVER} cluster to provision role/database"
sudo pg_ctlcluster "${PGVER}" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  sudo -u postgres pg_isready -q && break
  sleep 1
done

echo "==> [install] Ensuring 'titanbot' role and database exist"
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='titanbot'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE titanbot LOGIN PASSWORD 'password';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='titanbot'" | grep -q 1 \
  || sudo -u postgres createdb -O titanbot titanbot
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE titanbot TO titanbot;" >/dev/null

echo "==> [install] Installing Node dependencies (npm ci)"
npm ci

echo "==> [install] Writing local .env (only if missing)"
if [ ! -f .env ]; then
  cat > .env <<'ENVEOF'
# Local development .env generated by .cursor/install.sh (gitignored).
# Add a real DISCORD_TOKEN + CLIENT_ID to connect the bot to Discord.
DISCORD_TOKEN=
CLIENT_ID=
GUILD_ID=

NODE_ENV=development
LOG_LEVEL=info
LOG_TO_FILE=false

PORT=3000
WEB_HOST=0.0.0.0
PORT_RETRY_ATTEMPTS=5
CORS_ORIGIN=*

POSTGRES_URL=postgresql://titanbot:password@127.0.0.1:5432/titanbot
POSTGRES_SSL=false
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_DB=titanbot
POSTGRES_USER=titanbot
POSTGRES_PASSWORD=password

AUTO_MIGRATE=true
POSTGRES_MIGRATION_TABLE=schema_migrations
SCHEMA_VERSION=1
SCHEMA_VERSION_LABEL=baseline-v1

LAVALINK_NODES_FILE=lavalink/nodes.json
LAVALINK_SEARCH_PLATFORM=ytmsearch
LAVALINK_REST_VERSION=v4
ENVEOF
fi

# If Discord credentials were provided as secrets, surface them in .env so
# `npm start` can connect without manual edits.
if [ -n "${DISCORD_TOKEN:-}" ]; then
  sed -i "s|^DISCORD_TOKEN=.*|DISCORD_TOKEN=${DISCORD_TOKEN}|" .env
fi
if [ -n "${CLIENT_ID:-}" ]; then
  sed -i "s|^CLIENT_ID=.*|CLIENT_ID=${CLIENT_ID}|" .env
fi

echo "==> [install] Applying database schema (migrations)"
npm run migrate

echo "==> [install] Done."
